### ISSUE TITLE
Somthing was wrong during the fine-tuning process

### ISSUE THREAD

**Issue by tinaYA524** [NLPJCL/RAG-Retrieval#46]
The log is here,

```
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.18.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Batch size: 4
Start with seed: 666
Output dir: ./output/t2ranking_100_example
Model_name_or_path: ../../../BAAI/bge-base-zh-v1.5
Dataset: ../../../example_data/t2rank_100.jsonl
mixed_precision: fp16
gradient_accumulation_steps: 24
temperature: 0.02
log_with: wandb
neg_nums: 15
query_max_len: 128
passage_max_len: 512
use_mrl: False
mrl_dims: []
/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "train_embedding.py", line 194, in <module>
    main()
  File "train_embedding.py", line 123, in main
    model = accelerator.prepare(model)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 1350, in prepare
    result = tuple(
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 1351, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 1226, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 1495, in prepare_model
    self.state.fsdp_plugin.set_auto_wrap_policy(model)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/utils/dataclasses.py", line 1744, in set_auto_wrap_policy
    raise ValueError(f"Could not find the transformer layer class {layer_class} in the model.")
ValueError: Could not find the transformer layer class XLMRobertaLayer in the model.
[1;34mwandb[0m:
[1;34mwandb[0m: You can sync this run to the cloud by running:
[1;34mwandb[0m: [1mwandb sync /home/tina/Desktop/RAG-Retrieval-master/rag_retrieval/train/embedding/wandb/offline-run-20241120_102427-x6lgjhid[0m
[1;34mwandb[0m: Find logs at: [1;35mwandb/offline-run-20241120_102427-x6lgjhid/logs[0m
[2024-11-20 10:24:28,634] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 11850) of binary: /home/tina/anaconda3/envs/emb/bin/python
Traceback (most recent call last):
  File "/home/tina/anaconda3/envs/emb/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1155, in launch_command
    multi_gpu_launcher(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_embedding.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-20_10:24:28
  host      : tina-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11850)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by tinaYA524** [comment]
Now I have solved the above problem by obtaining the apikey of Wandb, but a new problem has arisen. I am seeking help from the gods to solve it!
The new log is here:
```
wandb: / Waiting for wandb.init()...
wandb: - Waiting for wandb.init()...
wandb: \ Waiting for wandb.init()...
wandb: | Waiting for wandb.init()...
wandb: / Waiting for wandb.init()...
wandb: - Waiting for wandb.init()...
wandb: ERROR Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
Traceback (most recent call last):
  File "train_embedding.py", line 188, in <module>
    main()
  File "train_embedding.py", line 85, in main
    accelerator.init_trackers('embedding', config=vars(args))
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 734, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 2701, in init_trackers
    self.trackers.append(tracker_init(project_name, **init_kwargs.get(str(tracker), {})))
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/tracking.py", line 81, in execute_on_main_process
    return function(self, *args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/tracking.py", line 298, in __init__
    self.run = wandb.init(project=self.run_name, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
[2024-11-20 09:56:34,453] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 10789) of binary: /home/tina/anaconda3/envs/emb/bin/python
Traceback (most recent call last):
  File "/home/tina/anaconda3/envs/emb/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1155, in launch_command
    multi_gpu_launcher(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_embedding.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-20_09:56:34
  host      : tina-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10789)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by NLPJCL** [comment]
https://github.com/NLPJCL/RAG-Retrieval/tree/master/rag_retrieval/train/embedding#:~:text=default_fsdp%E3%80%82%E5%A6%82%E6%9E%9C%E8%A6%81%E5%9C%A8chinese%2Droberta%2Dwwm%2Dext%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%8A%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E8%AE%AD%E7%BB%83%E7%9A%84%E6%8E%92%E5%BA%8F%EF%BC%8C%E9%87%87%E7%94%A8%E8%AF%A5%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E3%80%82

bge-base-zh-v1.5 should use this config.

**Comment by tinaYA524** [comment]
> https://github.com/NLPJCL/RAG-Retrieval/tree/master/rag_retrieval/train/embedding#:~:text=default_fsdp%E3%80%82%E5%A6%82%E6%9E%9C%E8%A6%81%E5%9C%A8chinese%2Droberta%2Dwwm%2Dext%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%8A%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E8%AE%AD%E7%BB%83%E7%9A%84%E6%8E%92%E5%BA%8F%EF%BC%8C%E9%87%87%E7%94%A8%E8%AF%A5%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E3%80%82
> 
> bge-base-zh-v1.5 should use this config.

I did run it according to the configuration requirements in this config, but due to poor network conditions, I downloaded the model locally and made some changes to address some bugs, such as
`
os.environ["WANDB_API_KEY"] = 'my-api-key'
os.environ["WANDB_MODE"] = "offline"
`
and
`num_processes: 1`
So what do you think could be the reason for the running failure?

**Comment by NLPJCL** [comment]
you can quickly fix this problem by: pip uninstall wandb.



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 20, 2024 11:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NLPJCL/RAG-Retrieval] Somthing was wrong during the fine-tuningprocess (Issue #46)




  
https://github.com/NLPJCL/RAG-Retrieval/tree/master/rag_retrieval/train/embedding#:~:text=default_fsdp%E3%80%82%E5%A6%82%E6%9E%9C%E8%A6%81%E5%9C%A8chinese%2Droberta%2Dwwm%2Dext%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%8A%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E8%AE%AD%E7%BB%83%E7%9A%84%E6%8E%92%E5%BA%8F%EF%BC%8C%E9%87%87%E7%94%A8%E8%AF%A5%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E3%80%82
 
bge-base-zh-v1.5 should use this config.
  
I did run it according to the configuration requirements in this config, but due to poor network conditions, I downloaded the model locally and made some changes to address some bugs, such as
 os.environ["WANDB_API_KEY"] = 'my-api-key' os.environ["WANDB_MODE"] = "offline"
 and
 num_processes: 1
 So what do you think could be the reason for the running failure?

**Comment by NLPJCL** [comment]
Please provide the new error log.
If it is a wandb configuration error, you can quickly solve it by uninstalling it

**Comment by tinaYA524** [comment]
> Please provide the new error log.
> If it is a wandb configuration error, you can quickly solve it by uninstalling it


But this is indeed the log that runs after uninstalling wandb. May I ask if this parameter needs to be modified: 
`-- logw_ith 'wandb'\`

**Comment by NLPJCL** [comment]
> > you can quickly fix this problem by: pip uninstall wandb.
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Wed, Nov 20, 2024 11:25 AM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [NLPJCL/RAG-Retrieval] Somthing was wrong during the fine-tuningprocess (Issue #46) https://github.com/NLPJCL/RAG-Retrieval/tree/master/rag_retrieval/train/embedding#:~:text=default_fsdp%E3%80%82%E5%A6%82%E6%9E%9C%E8%A6%81%E5%9C%A8chinese%2Droberta%2Dwwm%2Dext%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%8A%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E8%AE%AD%E7%BB%83%E7%9A%84%E6%8E%92%E5%BA%8F%EF%BC%8C%E9%87%87%E7%94%A8%E8%AF%A5%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E3%80%82 bge-base-zh-v1.5 should use this config. I did run it according to the configuration requirements in this config, but due to poor network conditions, I downloaded the model locally and made some changes to address some bugs, such as os.environ["WANDB_API_KEY"] = 'my-api-key' os.environ["WANDB_MODE"] = "offline" and num_processes: 1 So what do you think could be the reason for the running failure? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> After uninstalling Wandb and running it again, it still failed with the following log
> 
> ```
> /home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
>   warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
> Batch size: 4
> Start with seed: 666
> Output dir: ./output/t2ranking_100_example
> Model_name_or_path: ../../../BAAI/bge-base-zh-v1.5
> Dataset: ../../../example_data/t2rank_100.jsonl
> mixed_precision: fp16
> gradient_accumulation_steps: 24
> temperature: 0.02
> log_with: wandb
> neg_nums: 15
> query_max_len: 128
> passage_max_len: 512
> use_mrl: False
> mrl_dims: []
> /home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
>   return self.fget.__get__(instance, owner)()
> Traceback (most recent call last):
>   File "train_embedding.py", line 193, in <module>
>     main()
>   File "train_embedding.py", line 122, in main
>     model = accelerator.prepare(model)
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 1350, in prepare
>     result = tuple(
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 1351, in <genexpr>
>     self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 1226, in _prepare_one
>     return self.prepare_model(obj, device_placement=device_placement)
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py", line 1495, in prepare_model
>     self.state.fsdp_plugin.set_auto_wrap_policy(model)
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/utils/dataclasses.py", line 1744, in set_auto_wrap_policy
>     raise ValueError(f"Could not find the transformer layer class {layer_class} in the model.")
> ValueError: Could not find the transformer layer class XLMRobertaLayer in the model.
> [2024-11-20 13:20:29,463] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 30155) of binary: /home/tina/anaconda3/envs/emb/bin/python
> Traceback (most recent call last):
>   File "/home/tina/anaconda3/envs/emb/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
>     args.func(args)
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1155, in launch_command
>     multi_gpu_launcher(args)
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
>     distrib_run.run(args)
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
>     elastic_launch(
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> train_embedding.py FAILED
> ------------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-11-20_13:20:29
>   host      : tina-System-Product-Name
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 30155)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> ```

Please provide the contents of the bash file you executed.

**Comment by tinaYA524** [comment]
Here it is.
```
#!/bin/bash

if [ ! -d "./output" ]; then
    mkdir -p ./output
    echo "mkdir output"
fi

if [ ! -d "./logs" ]; then
    mkdir -p ./logs
    echo "mkdir logs"
fi

CUDA_VISIBLE_DEVICES="0"   nohup  accelerate launch --config_file ../../../config/xlmroberta_default_config.yaml train_embedding.py  \
--model_name_or_path "../../../BAAI/bge-base-zh-v1.5" \
--dataset "../../../example_data/t2rank_100.jsonl" \
--output_dir "./output/t2ranking_100_example" \
--batch_size 4 \
--lr 2e-5 \
--epochs 2 \
--save_on_epoch_end 1 \
--gradient_accumulation_steps 24  \
--log_with 'wandb' \
--warmup_proportion 0.1 \
--neg_nums 15 \
--temperature 0.02 \
--query_max_len 128 \
--passage_max_len 512 \
 >./logs/t2ranking_100_example.log 2>&1  &

```

**Comment by NLPJCL** [comment]
For BAAI/bge-base-zh-v1.5, replace
--config_file ../../../config/xlmroberta_default_config.yaml
with
--config_file ../../../config/default_fsdp.yaml

**Comment by tinaYA524** [comment]
> For BAAI/bge-base-zh-v1.5, replace --config_file ../../../config/xlmroberta_default_config.yaml with --config_file ../../../config/default_fsdp.yaml

The log of failed operation is shown below，
```
/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Batch size: 4
Start with seed: 666
Output dir: ./output/t2ranking_100_example
Model_name_or_path: ../../../BAAI/bge-base-zh-v1.5
Dataset: ../../../example_data/t2rank_100.jsonl
mixed_precision: fp16
gradient_accumulation_steps: 24
temperature: 0.02
log_with: wandb
neg_nums: 15
query_max_len: 128
passage_max_len: 512
use_mrl: False
mrl_dims: []
/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

0it [00:00, ?it/s]
100it [00:00, 17287.54it/s]
train_dataloader total is : 127
train_dataloader data_type is : triplet
Start training for 2 epochs

  0%|          | 0/127 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_embedding.py", line 193, in <module>
    main()
  File "train_embedding.py", line 181, in main
    trainer.train()
  File "/home/tina/Desktop/RAG-Retrieval-master/rag_retrieval/train/embedding/trainer.py", line 64, in train
    batch_output=self.model(**batch)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/utils/operations.py", line 820, in forward
    return model_forward(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/utils/operations.py", line 808, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/tina/Desktop/RAG-Retrieval-master/rag_retrieval/train/embedding/model.py", line 73, in forward
    neg_doc_embeddings = self.get_embedding(neg_doc_input_ids, neg_doc_attention_mask)
  File "/home/tina/Desktop/RAG-Retrieval-master/rag_retrieval/train/embedding/model.py", line 34, in get_embedding
    embedding = self.model(batch_text)['sentence_embedding']
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 688, in forward
    input = module(input, **module_kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/sentence_transformers/models/Transformer.py", line 350, in forward
    output_states = self.auto_model(**trans_features, **kwargs, return_dict=False)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1142, in forward
    encoder_outputs = self.encoder(
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/transformers/pytorch_utils.py", line 248, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 180.00 MiB. GPU 0 has a total capacty of 15.69 GiB of which 123.00 MiB is free. Including non-PyTorch memory, this process has 15.00 GiB memory in use. Of the allocated memory 14.47 GiB is allocated by PyTorch, and 91.11 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

  0%|          | 0/127 [00:00<?, ?it/s]
[2024-11-20 14:12:01,518] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 32901) of binary: /home/tina/anaconda3/envs/emb/bin/python
Traceback (most recent call last):
  File "/home/tina/anaconda3/envs/emb/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1155, in launch_command
    multi_gpu_launcher(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tina/anaconda3/envs/emb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_embedding.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-20_14:12:01
  host      : tina-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 32901)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by tinaYA524** [comment]
> For BAAI/bge-base-zh-v1.5, replace --config_file ../../../config/xlmroberta_default_config.yaml with --config_file ../../../config/default_fsdp.yaml

The problem has been solved, thank you very much！
