### ISSUE TITLE
微调reranker时，显示29500端口被占用，我怎么指定其他端口？

### ISSUE THREAD

**Issue by lxlx2084** [NLPJCL/RAG-Retrieval#50]
Traceback (most recent call last):
  File "/data/liuxiang/anaconda3/envs/rag/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/liuxiang/anaconda3/envs/rag/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/data/liuxiang/anaconda3/envs/rag/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1155, in launch_command
    multi_gpu_launcher(args)
  File "/data/liuxiang/anaconda3/envs/rag/lib/python3.8/site-packages/accelerate/commands/launch.py", line 771, in multi_gpu_launcher
    current_env = prepare_multi_gpu_env(args)
  File "/data/liuxiang/anaconda3/envs/rag/lib/python3.8/site-packages/accelerate/utils/launch.py", line 212, in prepare_multi_gpu_env
    raise ConnectionError(
ConnectionError: Tried to launch distributed communication on port `29500`, but another process is utilizing it. Please specify a different port (such as using the `--main_process_port` flag or specifying a different `main_process_port` in your config file) and rerun your script. To automatically use the next open port (on a single node), you can set this to `0`.

**Comment by lxlx2084** [comment]
> accelerate问题，之前已经启动过一个了。 在accelerate配置文件里面配置下：main_process_port。更换一个数字即可。

小白多问一下，我自己没有启用29500，如果服务器上的其他user也使用这个库，是他占用了这个端口吗？

**Comment by HuXiLiFeng** [comment]
> > accelerate问题，之前已经启动过一个了。 在accelerate配置文件里面配置下：main_process_port。更换一个数字即可。
> 
> 小白多问一下，我自己没有启用29500，如果服务器上的其他user也使用这个库，是他占用了这个端口吗？

端口可能是被其他人用其他程序占用的，倒不一定是说别人用这个库占用的。各自训练的时候按照@NLPJCL指定端口号就可以

**Comment by lxlx2084** [comment]
> > > accelerate问题，之前已经启动过一个了。 在accelerate配置文件里面配置下：main_process_port。更换一个数字即可。
> > 
> > 
> > 小白多问一下，我自己没有启用29500，如果服务器上的其他user也使用这个库，是他占用了这个端口吗？
> 
> 端口可能是被其他人用其他程序占用的，倒不一定是说别人用这个库占用的。各自训练的时候按照@NLPJCL指定端口号就可以

我不知道在哪里修改指定端口啊，哈哈哈对不起我有点菜

**Comment by NLPJCL** [comment]
这个其实是accelerate的配置问题，你可以在accelerate的config配置下。
