### ISSUE TITLE
bge-m3支持微调吗

### ISSUE THREAD

**Issue by Huang-zhenxuan** [NLPJCL/RAG-Retrieval#55]

**Comment by NLPJCL** [comment]
支持的。

**Comment by Huang-zhenxuan** [comment]
但是我运行脚本的时候报错了。
Traceback (most recent call last):
  File "/autodl-fs/data/2024BDCI_Conversation_RAG/code/RAG-Retrieval-master/rag_retrieval/train/embedding/train_embedding.py", line 188, in <module>
    main()
  File "/autodl-fs/data/2024BDCI_Conversation_RAG/code/RAG-Retrieval-master/rag_retrieval/train/embedding/train_embedding.py", line 117, in main
    model = accelerator.prepare(model)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1329, in prepare
    result = tuple(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1330, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1205, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1477, in prepare_model
    self.state.fsdp_plugin.set_auto_wrap_policy(model)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 1754, in set_auto_wrap_policy
    raise ValueError(f"Could not find the transformer layer class {layer_class} in the model.")
ValueError: Could not find the transformer layer class BertLayer in the model.




我的脚本：
#!/bin/bash

if [ ! -d "./output" ]; then
    mkdir -p ./output
    echo "mkdir output"
fi

if [ ! -d "./logs" ]; then
    mkdir -p ./logs
    echo "mkdir logs"
fi

CUDA_VISIBLE_DEVICES="0"   nohup  accelerate launch --config_file ../../../config/default_fsdp.yaml train_embedding.py  \
--model_name_or_path "/autodl-fs/data/2024BDCI_Conversation_RAG/model/bge-m3" \
--dataset "/autodl-fs/data/2024BDCI_Conversation_RAG/code/embed_train_data.jsonl" \
--output_dir "./output" \
--batch_size 16 \
--lr 2e-5 \
--epochs 2 \
--save_on_epoch_end 1 \
--gradient_accumulation_steps 24  \
--warmup_proportion 0.1 \
--temperature 0.02 \
--query_max_len 256 \
--passage_max_len -1 \
 >./logs/t2ranking_100_example.log

**Comment by NLPJCL** [comment]
参考：https://github.com/NLPJCL/RAG-Retrieval/tree/master/rag_retrieval/train/embedding#:~:text=xlmroberta_default_config%2C%E5%A6%82%E6%9E%9C%E8%A6%81%E5%9C%A8bge%2Dm3%2Dembedding%E5%92%8Cbce%2Dembedding%2Dbase_v1%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%8A%E8%BF%9B%E8%A1%8C%E5%BE%AE%E8%B0%83%EF%BC%8C%E9%87%87%E7%94%A8%E8%AF%A5%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%EF%BC%8C%E5%9B%A0%E4%B8%BA%E4%B8%A4%E8%80%85%E5%9C%A8%E5%A4%9A%E8%AF%AD%E8%A8%80%E7%9A%84xlmroberta%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%8A%E8%AE%AD%E7%BB%83%E8%80%8C%E6%9D%A5%E3%80%82

**Comment by Ziyang1060** [comment]
请使用 xlmroberta_default_config.yaml 配置文件

**Comment by Huang-zhenxuan** [comment]
> 请使用 xlmroberta_default_config.yaml 配置文件

好的感谢回答。已解决。
